# docker-compose.yml

version: '2'
services:
  MY_SUB_PROJECT_NAME:
    image: MY_SUB_PROJECT_NAME:0.1.0.0
    ports:
      - "3000:3000"
    links:
      - depend_service:depend_service
    user: MY_SUB_PROJECT_NAME
    environment:
      PARA1: XXXXX
      PARA2: YYYYY
    command: static_MY_SUB_PROJECT_NAME_nix_store_path/bin/MY_SUB_PROJECT_NAME
    volumes:
      - "MY_SUB_PROJECT_NAME_config_path:/var/MY_SUB_PROJECT_NAME/config"
      - "MY_SUB_PROJECT_NAME_data_path:/var/MY_SUB_PROJECT_NAME/data"
    depends_on:
      - depend_service
    restart: unless-stopped
  depend_service:
    build: depend_service
    ports:
      - "5432:5432"
    user: depend_service
    environment:
      DEPEND_SERVICE_PARA1: ZZZZ
    command: depend_service
    volumes:
      - "depend_service_path:/var/lib/depend_service_path"
      - "depend_service_data_path:/depend_service_data"
    restart: unless-stopped
